services:
  strapi:
    build:
      context: ./strapi
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    volumes:
      - ./strapi:/app/strapi # Mount Strapi directory
    environment:
      NODE_ENV: development
      DATABASE_CLIENT: sqlite
      DATABASE_FILENAME: .tmp/data.db
    networks:
      - strapi-net

  api-gateway:
    image: nginx:latest # 🎭 Our Nginx Maestro takes the stage!
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # 📜 Nginx configuration scroll
    depends_on:
      - strapi
    networks:
      - strapi-net

networks:
  strapi-net:
    driver: bridge