github.com:
    users:
        Ripnrip:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: Ripnrip
